name: 'Start/Stop service and rds'
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'infra-test'
        description: |
          🛑 DO NOT CHANGE THE DROPDOWN ABOVE FOR THE WORKFLOW. KEEP IT ON "main" BRANCH.
          --------------------------------------
          ⬇️ Environment.
        type: choice
        options:
          # - breakfix
          # - cps-preview
          - infra-test
          # - long
          # - performance
          # - stage
          # - test
          # - training
          # - trn2
          # - uat
      action:
        required: true
        default: 'stop-service'
        description: |
          ⬇️ action.
        type: choice
        options:
          - start-service
          - stop-service
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'
jobs:
  # deploy:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Dev Enviroments
        if: github.event.schedule != '0 7-19 * * 1-5'
        run: echo "This step will be run on Monday through Friday at 7am to 7pm"
      - name: UAT Enviroments
        if: github.event.schedule != '0 0 * * 1-5'
        run: echo "This step will be run on Monday through Friday at 24x5"
      - name: Prod Enviroments
        if: github.event.schedule != '0 0 * * 1-7'
        run: echo "This step will be run 24x7"
  start-service:
    if: github.event.inputs.action == 'start-service'
    runs-on: ubuntu-latest
    steps:
      - name: 'start-service'
        run:
          # echo "aws ecs start-task --task-definition massgov-pfml-${{ github.event.inputs.taskdefinition }} --cluster massgov-pfml-${{ github.event.inputs.cluster }}"
          echo "aws ecs update-service --service pf-api-${{ github.event.inputs.environment }} --desired-count 2"
          echo "aws ecs update-service --service pf-pdf-api-${{ github.event.inputs.environment }} --desired-count 2"
      - name: 'start rds'
        run: echo "aws rds start-db-instance --db-instance-identifier massgov-pfml-${{ github.event.inputs.environment }}"
  stop-service:
    if: github.event.inputs.action == 'stop-service'
    runs-on: ubuntu-latest
    steps:
      - name: 'stop service'
        run:
          # echo "aws ecs stop-task --task-definition massgov-pfml-${{ github.event.inputs.taskdefinition }} --cluster massgov-pfml-${{ github.event.inputs.cluster }}"
          echo "aws ecs update-service --service pf-api-${{ github.event.inputs.environment }} --desired-count 0"
          echo "aws ecs update-service --service pf-pdf-api-${{ github.event.inputs.environment }} --desired-count 0"
      - name: 'stop rds'
        run: echo "aws rds stop-db-instance --db-instance-identifier massgov-pfml-${{ github.event.inputs.environment }}"
